#!/bin/bash
# Reporte diario trial MCP actions — 2026-07-03
OUT="$(dirname "$0")/../outbox/mcp-trial-0703.out"
{
echo "=== flag ==="
grep MARIA_MCP_ACTIONS /root/secretaria/config/instances/maria-paez.conf || echo "FLAG AUSENTE"
echo ""
echo "=== mcp_fallback 24h (count) ==="
sqlite3 "$MARIA_DB" "SELECT COUNT(*) FROM eventos WHERE json_extract(metadata_json,'\$.tipo')='mcp_fallback' AND timestamp >= datetime('now','-24 hours');"
echo ""
echo "=== mcp_fallback 24h (detalle, ultimos 10) ==="
sqlite3 "$MARIA_DB" "SELECT timestamp, de, substr(cuerpo,1,300) FROM eventos WHERE json_extract(metadata_json,'\$.tipo')='mcp_fallback' AND timestamp >= datetime('now','-24 hours') ORDER BY timestamp DESC LIMIT 10;"
echo ""
echo "=== acciones ejecutadas OK 24h ==="
sqlite3 "$MARIA_DB" "SELECT COUNT(*) FROM eventos WHERE cuerpo LIKE 'acción ejecutada%' AND timestamp >= datetime('now','-24 hours');"
echo ""
echo "=== acciones FALLARON 24h ==="
sqlite3 "$MARIA_DB" "SELECT COUNT(*) FROM eventos WHERE cuerpo LIKE 'acción FALLÓ%' AND timestamp >= datetime('now','-24 hours');"
echo ""
echo "=== detalle fallas 24h (ultimas 10) ==="
sqlite3 "$MARIA_DB" "SELECT timestamp, de, substr(cuerpo,1,300) FROM eventos WHERE cuerpo LIKE 'acción FALLÓ%' AND timestamp >= datetime('now','-24 hours') ORDER BY timestamp DESC LIMIT 10;"
echo ""
echo "=== desglose acciones OK por tipo 24h ==="
sqlite3 "$MARIA_DB" "SELECT substr(cuerpo, 18, 40), COUNT(*) FROM eventos WHERE cuerpo LIKE 'acción ejecutada%' AND timestamp >= datetime('now','-24 hours') GROUP BY 1 ORDER BY 2 DESC;"
echo ""
echo "=== claude_call whatsapp 24h (turnos) ==="
sqlite3 "$MARIA_DB" "SELECT COUNT(*) FROM eventos WHERE json_extract(metadata_json,'\$.tipo')='claude_call' AND json_extract(metadata_json,'\$.canal')='whatsapp' AND timestamp >= datetime('now','-24 hours');"
echo ""
echo "=== claude_call whatsapp 24h (fallback si canal no esta en metadata) ==="
sqlite3 "$MARIA_DB" "SELECT COUNT(*) FROM eventos WHERE json_extract(metadata_json,'\$.tipo')='claude_call' AND timestamp >= datetime('now','-24 hours');"
} > "$OUT" 2>&1
