#!/bin/bash
set -u
DB="$MARIA_DB"
echo "== mcp_fallback 24h =="
sqlite3 "$DB" "SELECT COUNT(*) FROM eventos WHERE (tipo='mcp_fallback' OR json_extract(metadata_json,'\$.tipo')='mcp_fallback') AND timestamp >= datetime('now','-24 hours');"
echo "-- detalle (si hay) --"
sqlite3 "$DB" "SELECT datetime(timestamp,'localtime')||' | '||de||' | '||substr(cuerpo,1,250) FROM eventos WHERE (tipo='mcp_fallback' OR json_extract(metadata_json,'\$.tipo')='mcp_fallback') AND timestamp >= datetime('now','-24 hours') ORDER BY timestamp DESC LIMIT 10;"
echo "== acciones 24h (OK vs FALLO) =="
sqlite3 "$DB" "SELECT CASE WHEN cuerpo LIKE 'acción ejecutada%' THEN 'OK' ELSE 'FALLO' END, COUNT(*) FROM eventos WHERE (cuerpo LIKE 'acción ejecutada%' OR cuerpo LIKE 'acción FALLÓ%') AND timestamp >= datetime('now','-24 hours') GROUP BY 1;"
echo "-- tipos de acción ejecutados --"
sqlite3 "$DB" "SELECT substr(cuerpo,1,60), COUNT(*) FROM eventos WHERE cuerpo LIKE 'acción ejecutada%' AND timestamp >= datetime('now','-24 hours') GROUP BY 1 ORDER BY 2 DESC;"
echo "-- fallas detalle --"
sqlite3 "$DB" "SELECT datetime(timestamp,'localtime')||' | '||substr(cuerpo,1,250) FROM eventos WHERE cuerpo LIKE 'acción FALLÓ%' AND timestamp >= datetime('now','-24 hours') ORDER BY timestamp DESC LIMIT 10;"
echo "== flag MARIA_MCP_ACTIONS en .conf =="
grep MARIA_MCP_ACTIONS /root/secretaria/config/instances/maria-paez.conf || echo "(ausente — esperado post legacy-cleanup 2026-07-03: MCP es el único camino)"
echo "== claude_call whatsapp 24h =="
sqlite3 "$DB" "SELECT COUNT(*) FROM eventos WHERE (tipo='claude_call' OR json_extract(metadata_json,'\$.tipo')='claude_call') AND (json_extract(metadata_json,'\$.canal')='whatsapp' OR json_extract(metadata_json,'\$.canal_origen')='whatsapp') AND timestamp >= datetime('now','-24 hours');"
echo "-- claude_call por canal --"
sqlite3 "$DB" "SELECT COALESCE(json_extract(metadata_json,'\$.canal'),json_extract(metadata_json,'\$.canal_origen'),'?'), COUNT(*) FROM eventos WHERE (tipo='claude_call' OR json_extract(metadata_json,'\$.tipo')='claude_call') AND timestamp >= datetime('now','-24 hours') GROUP BY 1;"
echo "== fin =="
