#!/bin/bash
# Reporte diario trial MCP actions — 24h
DB="${MARIA_DB:?falta MARIA_DB}"
SQ() { sqlite3 "$DB" "$1"; }
echo "== mcp_fallback 24h =="
SQ "SELECT COUNT(*) FROM eventos WHERE json_extract(metadata_json,'\$.tipo')='mcp_fallback' AND timestamp >= datetime('now','-24 hours');"
echo "-- detalle fallbacks (si hay) --"
SQ "SELECT timestamp, substr(cuerpo,1,400) FROM eventos WHERE json_extract(metadata_json,'\$.tipo')='mcp_fallback' AND timestamp >= datetime('now','-24 hours') ORDER BY timestamp DESC LIMIT 10;"
echo "== acciones 24h =="
echo -n "OK: "; SQ "SELECT COUNT(*) FROM eventos WHERE cuerpo LIKE 'acción ejecutada%' AND timestamp >= datetime('now','-24 hours');"
echo -n "FALLÓ: "; SQ "SELECT COUNT(*) FROM eventos WHERE cuerpo LIKE 'acción FALLÓ%' AND timestamp >= datetime('now','-24 hours');"
echo "-- detalle fallas --"
SQ "SELECT timestamp, substr(cuerpo,1,300) FROM eventos WHERE cuerpo LIKE 'acción FALLÓ%' AND timestamp >= datetime('now','-24 hours') ORDER BY timestamp DESC LIMIT 10;"
echo "-- tipos de acción OK --"
SQ "SELECT substr(cuerpo,1,60), COUNT(*) FROM eventos WHERE cuerpo LIKE 'acción ejecutada%' AND timestamp >= datetime('now','-24 hours') GROUP BY 1 ORDER BY 2 DESC;"
echo "== flag .conf =="
grep MARIA_MCP_ACTIONS /root/secretaria/config/instances/maria-paez.conf || echo "(sin línea MARIA_MCP_ACTIONS)"
echo "== turnos claude_call 24h por canal =="
SQ "SELECT COALESCE(json_extract(metadata_json,'\$.canal'),'?'), COUNT(*) FROM eventos WHERE json_extract(metadata_json,'\$.tipo')='claude_call' AND timestamp >= datetime('now','-24 hours') GROUP BY 1;"
echo "== marker wa-apagado =="
ls -la /root/secretaria/state/maria-paez/wa-apagado 2>/dev/null || echo "(no existe — WA no apagado por marker)"
