#!/bin/bash
DB="$MARIA_DB"
echo "== DB: $DB =="
echo "== mcp_fallback 24h =="
sqlite3 "$DB" "SELECT COUNT(*) FROM eventos WHERE (tipo='mcp_fallback' OR json_extract(metadata_json,'$.tipo')='mcp_fallback') AND timestamp >= datetime('now','-24 hours');"
sqlite3 "$DB" "SELECT timestamp, de, substr(cuerpo,1,300) FROM eventos WHERE (tipo='mcp_fallback' OR json_extract(metadata_json,'$.tipo')='mcp_fallback') AND timestamp >= datetime('now','-24 hours') ORDER BY timestamp DESC LIMIT 10;"
echo "== acciones OK vs FALLO 24h =="
sqlite3 "$DB" "SELECT CASE WHEN cuerpo LIKE 'acción ejecutada%' THEN 'OK' ELSE 'FALLO' END k, COUNT(*) FROM eventos WHERE (cuerpo LIKE 'acción ejecutada%' OR cuerpo LIKE 'acción FALLÓ%') AND timestamp >= datetime('now','-24 hours') GROUP BY k;"
echo "-- detalle fallas --"
sqlite3 "$DB" "SELECT timestamp, substr(cuerpo,1,250) FROM eventos WHERE cuerpo LIKE 'acción FALLÓ%' AND timestamp >= datetime('now','-24 hours') ORDER BY timestamp;"
echo "-- tipos de accion ejecutados --"
sqlite3 "$DB" "SELECT substr(cuerpo,1,45), COUNT(*) FROM eventos WHERE cuerpo LIKE 'acción ejecutada%' AND timestamp >= datetime('now','-24 hours') GROUP BY 1 ORDER BY 2 DESC;"
echo "== flag en .conf =="
grep -n MARIA_MCP_ACTIONS /root/secretaria/config/instances/maria-paez.conf || echo "(sin linea MARIA_MCP_ACTIONS)"
echo "== claude_call whatsapp 24h =="
sqlite3 "$DB" "SELECT COUNT(*) FROM eventos WHERE (tipo='claude_call' OR json_extract(metadata_json,'$.tipo')='claude_call') AND json_extract(metadata_json,'$.canal')='whatsapp' AND timestamp >= datetime('now','-24 hours');"
echo "== fin =="
